- name: Add worker to swarm
 community.general.docker_swarm:
  state: join
  advertise_addr: swarm-worker
  join_token: "{{ hostvars ['swarm-manager']['swarm_data']['swarm_facts']['JoinTokens']['worker'] }}"
  remote_addrs: ["swarm-manager:2377"]
  
