- name: "Initialise the Swarm"
  docker_swarm:
    state: present
- name: "Get Swarm data"
  docker_swarm_data:
  register: swarm_data
- debug:
    msg: "Swarm data: {{ swarm_data }}"
- name: "Get worker token"
  add_host:
    name: "token"
    value: "{{ swarm_data['swarm_facts']['JoinTokens']['worker'] }}"